### ISSUE TITLE
Consider giving attribution

### ISSUE THREAD

**Issue by jsoendermann** [zoontek/react-native-dev-menu#1]
Since this project seems to be a modification of [react-native-dev-menu-item](https://github.com/jsoendermann/react-native-async-storage-dev-menu-item/), it would be nice if you could give proper attribution.

**Comment by zoontek** [comment]
@jsoendermann Indeed, https://github.com/jsoendermann/react-native-async-storage-dev-menu-item/ help me a lot for the native part (it's mostly undocumented). I add attribution in the README.
