### ISSUE TITLE
Yellowbox: Warning: Async Storage has been extracted from react-native core and will be removed in a future release

### ISSUE THREAD

**Issue by fungilation** [zoontek/react-native-dev-menu#13]
### Describe your environment

- React-Native version
0.59.9
- Platform: iOS, Android, both?
Both
- Device (which one?), simulator?
emulator
- OS version
macOS 10.15
- react-native-permissions version
- Devtools: Xcode? Android Studio version?
xcode 11.1, android studio 3.5
- (Android only: buildToolsVersion)
28.0.3

### How to repeat issue and example

Explain what you did, what you expected to happen, and what actually happens.
Provide some code if needed.

Just run app with this library installed, get yellowbox:
![image](https://user-images.githubusercontent.com/3803466/68064125-ed89ad00-fcd4-11e9-8b25-625dcd8b3feb.png)

```
Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage
```

### Solution

Do you know what needs to be done to address this issue? Ideally, provide a pull
request with a fix.

Native dependency needs updating to `@react-native-community/async-storage`

**Comment by zoontek** [comment]
@fungilation This package does not rely on Async Storage to works.
