### ISSUE TITLE
Consider adding a license?

### ISSUE THREAD

**Issue by jonlay-hanno** [zoontek/react-native-dev-menu#14]
Thanks for putting your time into this project 😄 

I didn't want to be presumptive and submit a PR, but would you consider adding a License?

I guess you're familiar with this from elsewhere and it's an oversight, but since there's no license, it seems GitHub considers that this is not an open-source project: https://choosealicense.com/no-permission/

**Comment by zoontek** [comment]
@jonlay-hanno Hi 👋. I chose [MIT](https://github.com/zoontek/react-native-dev-menu/blob/master/package.json), but forgot to add the LICENCE file 😅

If you create a PR with it, I will merge it ASAP!
