### ISSUE TITLE
Added menu multiplies on hot reload 

### ISSUE THREAD

**Issue by mi5ha** [zoontek/react-native-dev-menu#16]
When app is hot reloaded added menu shows multiple times.

Is there a way to check if menu is already added?

**Comment by zoontek** [comment]
Not yet, but it should be feasible 🙂

**Comment by mi5ha** [comment]
Update on this. It only happens when file where you added menu items is edited, for example App.tsx

When you change other files, and hot reload, it doesn't happen.

**Comment by zoontek** [comment]
Fixed in `4.0.1` 🎉 https://github.com/zoontek/react-native-dev-menu/releases/tag/4.0.1
