### ISSUE TITLE
native module cannot be null

### ISSUE THREAD

**Issue by yeomann** [zoontek/react-native-dev-menu#3]
* React-Native version
* Platform: iOS, Android, both
* Device: simulator: IOS Iphone 10.0 
* OS version Mac OS latest

I had red screen saying that `native module cannot be null` 

### Solution

It seems that after installing and linking, POD file was indeed added but `pod install` must be executed after `react-native link`as `pod install`.
As pod finished, I deleting app completely from emulator and re-run the `react-native run-ios` it started to working!

**Comment by zoontek** [comment]
If you have de `Podfile`, `react native link` will only add this in it. You have to run `pod install` after, it's normal.

**Comment by yeomann** [comment]
great:)
